// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OldVikings.Api.Database;

#nullable disable

namespace OldVikings.Api.Migrations
{
    [DbContext(typeof(OldVikingsContext))]
    [Migration("20260224070643_feedback_history")]
    partial class feedback_history
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OldVikings.Api.Database.Entities.FeedbackItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("DiscordAttempts")
                        .HasColumnType("int");

                    b.Property<long?>("DiscordChannelId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DiscordLastAttemptAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DiscordMessageId")
                        .HasColumnType("bigint");

                    b.Property<bool>("DiscordPosted")
                        .HasColumnType("bit");

                    b.Property<long?>("DiscordThreadId")
                        .HasColumnType("bigint");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("IsAnonymous")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("StatusMessage")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Title")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedByDiscordName")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<long?>("UpdatedByDiscordUserId")
                        .HasColumnType("bigint");

                    b.Property<int>("Visibility")
                        .HasColumnType("int");

                    b.Property<int>("VotesCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DiscordChannelId", "DiscordMessageId");

                    b.ToTable("Feedbacks");
                });

            modelBuilder.Entity("OldVikings.Api.Database.Entities.FeedbackStatusHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ChangedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("DiscordUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("DiscordUserName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid>("FeedbackItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("NewStatus")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("OldStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FeedbackItemId", "ChangedAtUtc");

                    b.ToTable("FeedbackStatusHistories");
                });

            modelBuilder.Entity("OldVikings.Api.Database.Entities.Greeting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AllianceName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Comment")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PlayerName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ServerNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Greetings");
                });

            modelBuilder.Entity("OldVikings.Api.Database.Entities.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Approved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("Registered")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("OldVikings.Api.Database.Entities.PoolLeader", b =>
                {
                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("BlockNextCycle")
                        .HasColumnType("bit");

                    b.Property<bool>("ForcePick")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("PlayerId");

                    b.ToTable("PoolLeaders");
                });

            modelBuilder.Entity("OldVikings.Api.Database.Entities.PoolVip", b =>
                {
                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("BlockNextCycle")
                        .HasColumnType("bit");

                    b.Property<bool>("ForcePick")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("PlayerId");

                    b.ToTable("PoolVips");
                });

            modelBuilder.Entity("OldVikings.Api.Database.Entities.R4Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.ToTable("R4Players");
                });

            modelBuilder.Entity("OldVikings.Api.Database.Entities.R4Roles", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.ToTable("R4Roles");
                });

            modelBuilder.Entity("OldVikings.Api.Database.Entities.ShinyServer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("FirstShinyDate")
                        .HasColumnType("date");

                    b.Property<int>("ServerNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ShinyServers");
                });

            modelBuilder.Entity("OldVikings.Api.Database.Entities.TrainGuide", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CurrentPlayerIndex")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("TrainGuides");
                });

            modelBuilder.Entity("OldVikings.Api.Database.Entities.WeeklySchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("WeekStartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("WeekStartDate")
                        .IsUnique();

                    b.ToTable("WeeklySchedules");
                });

            modelBuilder.Entity("OldVikings.Api.Database.Entities.WeeklyScheduleDay", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<Guid>("LeaderPlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ScheduleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("VipPlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("LeaderPlayerId");

                    b.HasIndex("VipPlayerId");

                    b.HasIndex("ScheduleId", "Date")
                        .IsUnique();

                    b.ToTable("WeeklyScheduleDays");
                });

            modelBuilder.Entity("OldVikings.Api.Database.Entities.FeedbackStatusHistory", b =>
                {
                    b.HasOne("OldVikings.Api.Database.Entities.FeedbackItem", "FeedbackItem")
                        .WithMany()
                        .HasForeignKey("FeedbackItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FeedbackItem");
                });

            modelBuilder.Entity("OldVikings.Api.Database.Entities.PoolLeader", b =>
                {
                    b.HasOne("OldVikings.Api.Database.Entities.Player", "Player")
                        .WithOne("PoolLeader")
                        .HasForeignKey("OldVikings.Api.Database.Entities.PoolLeader", "PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("OldVikings.Api.Database.Entities.PoolVip", b =>
                {
                    b.HasOne("OldVikings.Api.Database.Entities.Player", "Player")
                        .WithOne("PoolVip")
                        .HasForeignKey("OldVikings.Api.Database.Entities.PoolVip", "PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("OldVikings.Api.Database.Entities.WeeklyScheduleDay", b =>
                {
                    b.HasOne("OldVikings.Api.Database.Entities.Player", "LeaderPlayer")
                        .WithMany()
                        .HasForeignKey("LeaderPlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OldVikings.Api.Database.Entities.WeeklySchedule", "Schedule")
                        .WithMany("Days")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OldVikings.Api.Database.Entities.Player", "VipPlayer")
                        .WithMany()
                        .HasForeignKey("VipPlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LeaderPlayer");

                    b.Navigation("Schedule");

                    b.Navigation("VipPlayer");
                });

            modelBuilder.Entity("OldVikings.Api.Database.Entities.Player", b =>
                {
                    b.Navigation("PoolLeader");

                    b.Navigation("PoolVip");
                });

            modelBuilder.Entity("OldVikings.Api.Database.Entities.WeeklySchedule", b =>
                {
                    b.Navigation("Days");
                });
#pragma warning restore 612, 618
        }
    }
}
